#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# CONFIG DAS BORDAS E GAPS
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# CONFIG P/ O FOCO SEGUIR O MOUSE
bspc config focus_follows_pointer true

# CORES
#bspc config normal_border_color "#282c34"
#bspc config active_border_color "#98c379"
#bspc config focused_border_color "#c8ccd4"
#bspc config presel_feedback_color "#282c34"

# CORES PYWAL
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# COLORS
# . "${HOME}/.cache/wal/colors.sh"

# REGRA P/ SETAR O TEMA DO CURSOR
xsetroot -cursor_name left_ptr &

# INICIAR COM O SISTEMA
$HOME/.config/polybar/launch.sh

#$HOME/.fehbg
sh ~/.fehbg &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xrdb -merge ~/.Xresources

flameshot &

dunst &

numlockx on &

# REGRAS DE JANELA
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Urxvt state=floating follow=off
bspc rule -a Pcmanfm state=floating follow=off
bspc rule -a mpv state=floating follow=off
bspc rule -a Lxappearance state=floating follow=off
bspc rule -a Mousepad state=floating follow=off
bspc rule -a Pavucontrol state=floating follow=off
bspc rule -a Atril state=floating follow=off
bspc rule -a Gnome-calculator state=floating follow=off
bspc rule -a Feh state=floating follow=off
bspc rule -a Kitty state=floating follow=off



