#!/bin/bash

# Find the current user.
whoami=$(whoami)

# Ask for ISO file path.
echo "Insira o caminho da ISO para gravar."
echo "Por exemplo: ~/Downloads/archlinux.iso"
read iso

# Verify ISO path.
if [ ! -f "$iso" ]; then
    echo "O caminho do arquivo ISO é inválido. Por favor, verifique e tente novamente."
    exit 1
fi

# List available devices and ask for device to be used.
echo "Se você não sabe qual a partição do drive a ser usado, escolha qual drive será usado."
lsblk
echo "Informe qual o drive será usado."
echo "Por exemplo: /dev/sdx (troque o x pela letra correspondente)"
read drive

# Verify device path.
if [ ! -b "$drive" ]; then
    echo "O caminho do dispositivo é inválido. Por favor, verifique e tente novamente."
    exit 1
fi

# Ask for confirmation before starting the copy process.
echo "Você tem certeza de que deseja iniciar a gravação do ISO em $drive?"
echo "Digite 'sim' para confirmar ou qualquer outra tecla para cancelar."
read -r confirm

if [ "$confirm" != "sim" ]; then
    echo "A gravação do ISO foi cancelada."
    exit 1
fi

# Verify write permission.
if [ ! -w "$drive" ]; then
    echo "Você não tem permissão para gravar neste dispositivo. Por favor, execute o script como root ou como um usuário com permissão de gravação no dispositivo."
    exit 1
fi

# Start copy process.
echo "Iniciando gravação, aguarde..."
dd if="$iso" of="$drive" bs=4M oflag=sync status=progress

# Print message when copy process is completed.
echo "Gravação concluída."
